### ISSUE TITLE
No such file or directory: '/content/DeepDreamAnim/models/bvlc_googlenet/deploy.prototxt'

### ISSUE THREAD

**Issue by Colliwomple** [aertist/DeepDreamAnimV2#1]
Hi ! When starting to dream i get "FileNotFoundError: [Errno 2] No such file or directory: '/content/DeepDreamAnim/models/bvlc_googlenet/deploy.prototxt'" Any idea whats wrong ??
Full error:
"Traceback (most recent call last):
  File "dreamer.py", line 533, in <module>
    args.zoom, args.stepsize, args.blendflow, args.blendstatic, args.layers, args.guide, args.gpu, args.flow, args.flowthresh, args.divide, args.maxWidth, args.maxHeight, args.modeln)
  File "dreamer.py", line 281, in main
    text_format.Merge(open(net_fn).read(), model)
FileNotFoundError: [Errno 2] No such file or directory: '/content/DeepDreamAnim/models/bvlc_googlenet/deploy.prototxt'
" Ubuntu 20.04 RTX 2080 TI

**Comment by aertist** [comment]
I recommend running this code in google colab. Colab notebook is included in the repo.
The problem you are facing is because of this [line](https://github.com/aertist/DeepDreamAnimV2/blob/95983e0df0e973695b2e2c7550131a0687e35a94/dreamer.py#L253)

The code was setup to run in google colab by default. 
You can change that line but then you will have to download the `bvlc_googlenet` model from the [Caffe Model Zoo](https://github.com/BVLC/caffe/wiki/Model-Zoo#berkeley-trained-models) and place it in the `models/bvlc_googlenet/bvlc_googlenet.caffemodel` directory.

Check out [this](https://www.reddit.com/r/deepdream/comments/lesdwm/developing_an_after_effects_plugin_for_deep/?utm_source=share&utm_medium=web2x&context=3) reddit post for the context of this repo.

P.S. This code is still under development. You can contribute if you want :)

**Comment by Colliwomple** [comment]
Mate ! Thx for the fast help ! Will change the line and hoping i can make it work. Can i run this on my 2080 TI ?? Or will it be too slow ?

**Comment by aertist** [comment]
> Mate ! Thx for the fast help ! Will change the line and hoping i can make it work. Can i run this on my 2080 TI ?? Or will it be too slow ?

It depends on the resolution of your video.
I recommend starting with a 9:16 (Tik Tok/Instagram Reels) resolution.

Main parameters you should use for a decent amount of dreaming:
`3 octaves, 4 iteration per octave, 1.2 octave scale and flow 1`

This code is under development. It will give errors. If you resolve them please send a PR I will be more than happy to merge.

**Comment by Colliwomple** [comment]
I wish i am good enough to help you but still a noob !

**Comment by Colliwomple** [comment]
Just tested out the colab. Not working for me :-(

**Comment by aertist** [comment]
Yeah as I said it still needs cleaning. Check the comments of that reddit post. I discussed the problems there.
In the mean time you can watch the repo. 😅
